# Generated by Django 3.2.5 on 2021-08-04 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('descr', models.CharField(max_length=200, verbose_name='Description')),
                ('body', models.TextField(verbose_name='Post Body')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Travel', 'Travel'), ('Lifestyle', 'Lifestyle'), ('Fashion', 'Fashion')], default='Food', max_length=20)),
                ('slug', models.SlugField(default='my-post-name')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('username', models.CharField(default='anonymous', max_length=100)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainblog.post')),
            ],
        ),
    ]
