# Generated by Django 3.2.6 on 2021-08-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainblog', '0002_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='my-post-name', max_length=200),
        ),
    ]
